spring:
server:
  port: 0
eureka:
  instance:
    prefer-ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka

cursos:
  urlBase: ${URL_BASE_CURSO:http://servicio-cursos}
  username: user3
  password: user3
